# Generated by Django 5.1.1 on 2024-11-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_initial'),
        ('reptrack_trace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_as_representative', to='users.user'),
        ),
        migrations.AddField(
            model_name='report',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_for_shop', to='reptrack_trace.shop'),
        ),
    ]
