# Generated by Django 5.1.2 on 2025-04-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='main_store',
        ),
    ]
