# Generated by Django 5.1.1 on 2024-11-22 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_phone', models.CharField(max_length=20)),
                ('manager_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_phone', models.CharField(max_length=20)),
                ('manager_email', models.EmailField(max_length=254)),
                ('store_manager_name', models.CharField(max_length=255)),
                ('store_manager_phone', models.CharField(max_length=20)),
                ('store_manager_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('shop', 'Shop'), ('store', 'Store'), ('main_store', 'Main Store')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('main_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reptrack_trace.mainstore')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptrack_trace.product')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_current_quantity', models.IntegerField()),
                ('needs_topup', models.BooleanField()),
                ('desired_quantity', models.IntegerField(blank=True, null=True)),
                ('topup_quantity', models.IntegerField(blank=True, null=True)),
                ('shop_photo', models.ImageField(upload_to='shop_photos/')),
                ('shop_comments', models.TextField(blank=True)),
                ('store_manager_confirmed', models.BooleanField(default=False)),
                ('store_current_quantity', models.IntegerField(blank=True, null=True)),
                ('has_sufficient_stock', models.BooleanField(null=True)),
                ('quantity_taken_from_store', models.IntegerField(blank=True, null=True)),
                ('remaining_store_quantity', models.IntegerField(blank=True, null=True)),
                ('store_photo', models.ImageField(blank=True, null=True, upload_to='store_photos/')),
                ('store_comments', models.TextField(blank=True)),
                ('main_store_quantity', models.IntegerField(blank=True, null=True)),
                ('quantity_taken_from_main', models.IntegerField(blank=True, null=True)),
                ('remaining_main_quantity', models.IntegerField(blank=True, null=True)),
                ('main_store_photo', models.ImageField(blank=True, null=True, upload_to='main_store_photos/')),
                ('main_store_comments', models.TextField(blank=True)),
                ('final_shop_quantity', models.IntegerField(blank=True, null=True)),
                ('final_store_quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('main_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reptrack_trace.mainstore')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptrack_trace.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
