# Generated by Django 5.1.4 on 2025-01-04 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_phone', models.CharField(max_length=20)),
                ('manager_email', models.EmailField(max_length=254)),
                ('store_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_manager_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('store_manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='remaining_main_quantity',
            new_name='quantity_taken_from_main_store',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='has_sufficient_stock',
            new_name='shop_store_has_sufficient_stock',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='store_manager_confirmed',
            new_name='shop_store_manager_confirmed',
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reptrack_trace.report'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reptrack_trace.shop'),
        ),
        migrations.AddField(
            model_name='report',
            name='current_shop_photo',
            field=models.ImageField(blank=True, null=True, upload_to='store_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='quantity_taken_from_shop_store',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='remaining_main_store_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='remaining_shop_store_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='representative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reptrack_trace.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='shop_photo_update',
            field=models.ImageField(blank=True, null=True, upload_to='shop_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='shop_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='shop_store_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='shop_store_current_quantity',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='shop_store_photo',
            field=models.ImageField(blank=True, null=True, upload_to='store_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='shop_update_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='was_shop_updated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='store_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='store_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='store_manager_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'location_type', 'shop', 'main_store')},
        ),
        migrations.CreateModel(
            name='ShopStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_taken', models.IntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_stores', to='reptrack_trace.shop')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reptrack_trace.store'),
        ),
    ]
