# Generated by Django 5.1.4 on 2025-01-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0002_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='store',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='store_photo',
            new_name='current_shop_store_photo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quantity_taken_from_store',
        ),
        migrations.RemoveField(
            model_name='report',
            name='remaining_store_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='store_comments',
        ),
        migrations.RemoveField(
            model_name='report',
            name='store_current_quantity',
        ),
        migrations.AlterField(
            model_name='report',
            name='shop_store_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_store_photos/'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
