# Generated by Django 5.1.4 on 2024-12-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0002_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='manager_phone',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_manager_name',
        ),
    ]
