# Generated by Django 5.1.4 on 2025-01-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0003_remove_report_manager_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopstore',
            name='quantity_taken',
        ),
    ]
