# Generated by Django 5.1.4 on 2025-01-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0003_remove_report_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='delivered_to_shop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='delivered_to_shop_stores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='quantity_in_shopstores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_quantity_in_shop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
