# Generated by Django 5.1.4 on 2025-01-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0004_remove_shopstore_quantity_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstore',
            name='quantity_taken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
