# Generated by Django 5.1.4 on 2025-01-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0005_report_was_shop_m_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='shop_update_quantity',
            new_name='shop_store_update_quantity',
        ),
    ]
