# Generated by Django 5.1.4 on 2025-01-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0006_rename_shop_update_quantity_report_shop_store_update_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='shop_store_update_quantity',
            new_name='shop_update_quantity',
        ),
    ]
