# Generated by Django 5.1.4 on 2025-01-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0008_alter_report_shop_store_current_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='main_store_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='shop_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='shop_store_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
