# Generated by Django 5.1.4 on 2025-01-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0009_report_main_store_photo_taken_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='current_shop_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='current_shop_store_photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
