# Generated by Django 5.1.4 on 2025-01-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0010_report_current_shop_photo_taken_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='shop_photo_update_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
