# Generated by Django 5.1.4 on 2025-01-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0012_remove_report_shop_photo_update_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='shop_photo_update_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
