# Generated by Django 5.1.2 on 2025-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_main_store'),
        ('reptrack_trace', '0014_rename_shop_photo_update_taken_at_report_shop_update_photo_taken_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='main_store',
        ),
        migrations.RemoveField(
            model_name='shopstore',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='report',
            name='current_shop_photo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='current_shop_photo_taken_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='current_shop_store_photo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='current_shop_store_photo_taken_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='delivered_to_shop',
        ),
        migrations.RemoveField(
            model_name='report',
            name='delivered_to_shop_stores',
        ),
        migrations.RemoveField(
            model_name='report',
            name='desired_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='final_shop_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='final_store_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='main_store_comments',
        ),
        migrations.RemoveField(
            model_name='report',
            name='main_store_photo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='main_store_photo_taken_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='main_store_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='needs_topup',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quantity_in_shopstores',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quantity_taken_from_main',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quantity_taken_from_main_store',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quantity_taken_from_shop_store',
        ),
        migrations.RemoveField(
            model_name='report',
            name='remaining_main_store_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='remaining_shop_store_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_photo_update',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_store_comments',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_store_current_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_store_has_sufficient_stock',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_store_manager_confirmed',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_store_photo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_store_photo_taken_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_update_photo_taken_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='shop_update_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='topup_quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_quantity_in_shop',
        ),
        migrations.RemoveField(
            model_name='report',
            name='was_shop_m_updated',
        ),
        migrations.RemoveField(
            model_name='report',
            name='was_shop_stores_updated',
        ),
        migrations.RemoveField(
            model_name='report',
            name='was_shop_updated',
        ),
        migrations.AddField(
            model_name='report',
            name='after_merch_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='after_merch_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='after_merch_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='after_merch_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='after_merch_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='before_merch_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='before_merch_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='before_merch_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='before_merch_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='before_merch_photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='merch_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='merchandising_comment',
            field=models.TextField(blank=True, help_text='Comments on merchandising actions taken.'),
        ),
        migrations.AddField(
            model_name='report',
            name='po_photo',
            field=models.ImageField(blank=True, help_text='Picture of the Purchase Order (P.O) if applicable.', null=True, upload_to='po_photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='stock_file_quantity',
            field=models.IntegerField(help_text='Quantity written on the stock file.', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='shop_comments',
            field=models.TextField(blank=True, help_text="Comment or resolution for any stock discrepancy found (Maps to 'Comment/Resolution' in PDF)."),
        ),
        migrations.AlterField(
            model_name='report',
            name='shop_current_quantity',
            field=models.IntegerField(help_text="Current quantity physically counted in the shop (Maps to 'Current Quantity Found' in PDF)."),
        ),
        migrations.AlterField(
            model_name='report',
            name='shop_photo',
            field=models.ImageField(help_text="Picture of the physical stock file/sheet (Previously 'Shop Shelf Photo').", upload_to='stock_file_photos/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='shop_photo_taken_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='MainStore',
        ),
        migrations.DeleteModel(
            name='ShopStore',
        ),
    ]
