# Generated by Django 5.1.2 on 2025-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0015_remove_report_main_store_remove_shopstore_shop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='shop_photo',
            new_name='stock_file_photo',
        ),
        migrations.AlterField(
            model_name='report',
            name='po_photo',
            field=models.ImageField(blank=True, help_text='Take a picture of the P.O if Applicable', null=True, upload_to='po_photos/'),
        ),
    ]
