# Generated by Django 5.2.1 on 2025-05-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0016_rename_shop_photo_report_stock_file_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='discrepancy',
            field=models.IntegerField(blank=True, help_text='Auto calculated discrepancy between stock file and current quantity', null=True),
        ),
    ]
