# Generated by Django 5.2.1 on 2025-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptrack_trace', '0018_alter_report_stock_file_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='stock_file_quantity',
            field=models.IntegerField(help_text='Quantity written on the stock file.', null=True),
        ),
    ]
